apiVersion: v1
kind: Secret
metadata:
  name: default-tls-cert
  namespace: traefik
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDDzCCAfegAwIBAgIUK0hIrnRKoXs9RmBv1aaPG8v5vSwwDQYJKoZIhvcNAQEL
    BQAwFzEVMBMGA1UEAwwMY2xvdWRuZXNzLmlvMB4XDTI1MTIwMjA2NTUyNFoXDTM1
    MTIwMjA2NTUyNFowFzEVMBMGA1UEAwwMY2xvdWRuZXNzLmlvMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmoY/VFrewW8VBLvaNpCmX8QFxW0Ab5HjuOEL
    Z2nkPIG7SiwUXJHq6UOvgEDDtJKBxYV9kJYYXYLxw19Uf88BeE05ozhAZxe6ME0n
    HyBVsoss1E04uPkUkIZ1XrKfCJlRNodPoMbQNhvnMDFvveKcCNpg0D2QBjkTYvPa
    EYjpwzlaxwtkxdt9KiRdmGXfdJRPnpixspMlpkkQCeOZsbAZtUBd2GubK9HWVtRw
    NcYdGl8/Iyi5SrIexStpzlyLKaJHmz8A0kcb/FMeAS91x1dZ0l0SHe/cXoP/JFZv
    J7UEc+ISPfBr9uIAQOHsOEp6JCXzGo5OUPvPKL2hZ4O4o4OwWQIDAQABo1MwUTAd
    BgNVHQ4EFgQUjYF89m2eheXIt0Wc4IIRLwTt38YwHwYDVR0jBBgwFoAUjYF89m2e
    heXIt0Wc4IIRLwTt38YwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
    AQEAO7fhPL7yc1qqFdG2x/SkrpGuaHXCI6bEJD4Ds4PDvHWN/9sacffDx1hk5Za+
    L7xlwAGpJKbzrcLMaz7mIaeA+ha/P+n+6IN208u1QhtxoI2DU9kMEMFRMZDzfWZl
    6COcZKtNcdvU1w4UPl0TZ2ROwQ0ccBXSTTVFy8DLmJ5BpVt2qyaWEy47oulDqaMl
    +rVSEf96LbvHIPpyU3n7iExjJJKYbhhC13LdAZBIXf55Jrn7vDf9CuIuTrRBLrNG
    Rr/u/S/JiasrY4ltUnJguv8zHygsSnoIYz5wWtS3lMIVqPf3q3ZhT1s/1Qr/+tTn
    Sh7TBzH+uCRApSBimQp4SE0kvQ==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCahj9UWt7BbxUE
    u9o2kKZfxAXFbQBvkeO44QtnaeQ8gbtKLBRckerpQ6+AQMO0koHFhX2QlhhdgvHD
    X1R/zwF4TTmjOEBnF7owTScfIFWyiyzUTTi4+RSQhnVesp8ImVE2h0+gxtA2G+cw
    MW+94pwI2mDQPZAGORNi89oRiOnDOVrHC2TF230qJF2YZd90lE+emLGykyWmSRAJ
    45mxsBm1QF3Ya5sr0dZW1HA1xh0aXz8jKLlKsh7FK2nOXIspokebPwDSRxv8Ux4B
    L3XHV1nSXRId79xeg/8kVm8ntQRz4hI98Gv24gBA4ew4SnokJfMajk5Q+88ovaFn
    g7ijg7BZAgMBAAECggEAPjz5MARDuVyA9j2leBnN8T+WZXzwUn/L3XDDM51qgNZt
    9cOIVfqtx9Nr0jgDu2zRGRoZx4009iEiOGNiuPHLMUXFg9DJ29wqMX851SckbTvy
    S/ZodNRaLJYDmydNt9xs4g4hC+xX+5tEhFw9Ghm2aDhxCx7oriD6Bn6aZDqlkOwd
    xORUn0xMDIjts/SH8H52VFi4RiAKeVt6/exp2ep474LVaZ3PjPr495qxO7WTHoAc
    Zn51t6dsKIHUPU7nLAxvJKEwWPBFDu/X4IumnNvwm1NpINwNzatGi4VfgNiJdAWD
    wPqL3LgqXh5wflrAXhkoXiBSJXiXIfDYSz9YoQqLwwKBgQDXNRwdkc40G+3LqXhY
    YSq72z1CXg/SvcUFNkTG5caGVNeXNubqlfEQT7q/kozm1Fg+Siz1s39VSZEWj47o
    2YhCymP9qigpOsLtsXqXGAySabqwzTQ57Kp1HL2EGjcQhXeE90kroR12+myyteIa
    ujUALdLV6dYXzUeFdpVxWwAP+wKBgQC30IHBbx10L29MNXYDID++2Dj017j0Scju
    MsVaF/y7LulgIWvts3eYsoUzmpHU29MKgE3QZqINVlyVbMWIBXo1h5FDHZAuJqxg
    5VX2ES+PpWJN4J/LS+UWdSFWpJ1blfB47xg1W99cWuEkEY00XCFyBIK2pzdwVPCD
    bim5oHTMuwKBgA7xwjUPdflKYzX8W74PaU9IRzW/oGuq/+5/uUDyndmgNKRsjJaH
    uQi/8KDzBVPWNRaGQh8ByvraM/gUGgFzcbHpqg3obgeG7BhjdbbeVakpLGywo0rO
    c3vUdhihVWeRTR5vqaYc9xXXCAtU9BGVEq8jf3uZVGOsvqW2+WO4xQVXAoGAKmnQ
    JuQOtcpkMf979YixbMXTjptgL+3+kQfiBcHXLRHMA8RydOyeQfufRKL711PJxHiK
    e/XSmqU8w7XPdm1dH5DiccwWgq+lws3oIdkhUlHk9vdHp88hUyc/xBBDxug4Do+M
    1HMYfOTzYjEylcxUY0yrJJ486oyO2qTGt/BQQxUCgYEA0nAlef/MjPnc0M0oQyM6
    GDYjx3BfDLpBJmDgcGrrUQMW+i+3ARpkKqCrsTZ5tmKsjZBxjT9yEn9gwdXBKzaR
    7cvKVc4zR4pjSMktmNUT/TVLjGdvUMspOoO9f2j3uqbC1bVhf2qxiKJyO+F/BDCe
    W5ztcAH6r7wRF63YPmG4bS4=
    -----END PRIVATE KEY-----